version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.0
  aws-ecr: circleci/aws-ecr@3.1.0
  kubernetes: circleci/kubernetes@0.3.0

jobs:
  lint:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Run lint
          command: |
            cd src
            npm install
            npm run lint

  build-and-push-image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Build application Docker image
          command: |
            export IMAGE_NAME=node-web-app:0.1.${CIRCLE_BUILD_NUM}
            cd src
            docker build -t ${AWS_ECR_URL}/${IMAGE_NAME} .
            docker tag ${AWS_ECR_URL}/${IMAGE_NAME} "${AWS_ECR_URL}/${IMAGE_NAME}"
            login="$(aws ecr get-login)"
            ${login}
            docker push "${AWS_ECR_URL}/${IMAGE_NAME}"

  deploy-application:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      docker-image-name:
        description: |
          Name of the docker image to be deployed
        type: string
      version-info:
        description: |
          App version information
        type: string
      aws-region:
        description: |
          AWS region
        type: string
        default: "us-east-1"
    steps:
      - checkout
      - run:
          name: Create deployment manifest
          command: |
            BUILD_DATE=$(date '+%Y%m%d%H%M%S')
            cat deployment/app-deployment.yaml.template | \
               sed "s|DOCKER_IMAGE_NAME|<< parameters.docker-image-name >>| \
                g;s|BUILD_DATE_VALUE|$BUILD_DATE|g;s|VERSION_INFO_VALUE| \
                << parameters.version-info >>|g" > deployment/app-deployment.yaml
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          aws-region: << parameters.aws-region >>
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/app-deployment.yaml"
          get-rollout-status: true
          resource-name: deployment/nodeapp
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/app-service.yaml"

workflows:
  deployment:
    jobs:
      - lint
      - build-and-push-image:
          requires: [lint]
      - deploy-application:
          cluster-name: EKS-Capstone
          aws-region: $AWS_DEFAULT_REGION
          docker-image-name: "${AWS_ECR_URL}/node-web-app:0.1.${CIRCLE_PREVIOUS_BUILD_NUM}"
          version-info: "${CIRCLE_SHA1}"
          requires: 
            - build-and-push-image