version: 2.1
  
jobs:
  create-eks-cluster:
    docker:
      - image: swheat320/docker-node-py-tf:1.0
    steps:
      - checkout
      - run: 
          name: Deploy EKS via terraform
          command: |
            terraform -chdir=terraform init -reconfigure
            terraform -chdir=terraform validate
            terraform -chdir=terraform plan -out "planfile"
            terraform -chdir=terraform apply -input=false "planfile"

workflows:
  deployment:
    jobs:
      - create-eks-cluster
      