version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.0
  aws-ecr: circleci/aws-ecr@3.1.0
  kubernetes: circleci/kubernetes@0.3.0

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
          name: Build and push docker image
          command: |
            export IMAGE_NAME=node-web-app:0.1.${CIRCLE_BUILD_NUM}
            echo "$DOCKER_PWD" | docker login --username $DOCKER_LOGIN --password-stdin
            cd src
            docker build -t $DOCKER_LOGIN/$IMAGE_NAME .
            docker push $DOCKER_LOGIN/$IMAGE_NAME

  deploy-application:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      docker-image-name:
        description: |
          Name of the docker image to be deployed
        type: string
      version-info:
        description: |
          App version information
        type: string
      aws-region:
        description: |
          AWS region
        type: string
        default: "us-east-1"
    steps:
      - checkout
      - run:
          name: Create deployment manifest
          command: |
            BUILD_DATE=$(date '+%Y%m%d%H%M%S')
            cat deployment/app-deployment.yaml.template | \
               sed "s|DOCKER_IMAGE_NAME|<< parameters.docker-image-name >>| \
                g;s|BUILD_DATE_VALUE|$BUILD_DATE|g;s|VERSION_INFO_VALUE| \
                << parameters.version-info >>|g" > deployment/app-deployment.yaml
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          aws-region: << parameters.aws-region >>
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/app-deployment.yaml"
          get-rollout-status: true
          resource-name: deployment/nodeapp
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/app-service.yaml"

workflows:
  deployment:
    jobs:
      - build         
      - deploy-application:
          cluster-name: EKS-Capstone
          aws-region: us-east-1
          docker-image-name: "kevinluu10/node-web-app:latest"
          version-info: "${CIRCLE_SHA1}"
          requires: [build]