version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2
  helm: circleci/helm@1.0

jobs:

  delete-helm-release:
    executor: aws-eks/python
    parameters:
      cluster-name:
        description: Cluster name
        type: string
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - helm/install-helm-client:
          version: v2.16.9
      - run:
          command: |
            helm repo add stable http://cncf.gitlab.io/stable
          name: Add cncf stable repo
      - helm/delete-helm-release:
          purge: true
          release-name: prometheus-release
          timeout: 600

  install-helm-chart:
    executor: aws-eks/python
    parameters:
      cluster-name:
        description: Cluster name
        type: string
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - helm/install-helm-client:
          version: v2.16.9
      - run:
          command: |
            helm repo add stable http://cncf.gitlab.io/stable
          name: Add cncf stable repo
      - helm/install-helm-chart:
          chart: stable/prometheus
          release-name: prometheus-release
          
  install-helm-on-cluster:
    executor: aws-eks/python
    parameters:
      cluster-name:
        description: Cluster name
        type: string
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - helm/install-helm-on-cluster:
          enable-cluster-wide-admin-access: true

workflows:
  deployment:
    jobs:
      - aws-eks/create-cluster:
          cluster-name: test-cluster
      - install-helm-on-cluster:
          cluster-name: test-cluster
          requires:
            - aws-eks/create-cluster
      - install-helm-chart:
          cluster-name: test-cluster
          requires:
            - install-helm-on-cluster
      - delete-helm-release:
          cluster-name: test-cluster
          requires:
            - install-helm-chart
      - aws-eks/delete-cluster:
          cluster-name: test-cluster
          requires:
            - delete-helm-release
          wait: true
